import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    en: {
        // General
        home: 'Home',
        discoveries: 'Discoveries',
        myDiscoveries: 'My Discoveries',
        community: 'Community',
        map: 'Map',
        experts: 'Experts',
        reports: 'Reports',
        statistics: 'Statistics',
        settings: 'Settings',
        admin: 'Admin',
        editLabel: 'Edit label',
        editTimeLabel: 'Edit time label',
        useMyLocation: 'Use My Location',
        geoNotSupported: 'Geolocation is not supported by your browser',
        geoError: 'Unable to retrieve your location',
        
        // Home
        welcome: 'Archeos',
        tagline: 'Discover, identify, and document archaeological finds with AI-powered analysis',
        newDiscovery: 'New Discovery',
        viewMap: 'View Map',
        contactExpert: 'Contact Expert',
        totalDiscoveries: 'Total Discoveries',
        identified: 'Identified',
        reportsFiled: 'Reports Filed',
        recentDiscoveries: 'Recent Discoveries',
        viewAll: 'View All',
        noDiscoveries: 'No discoveries yet',
        startBy: 'Start by uploading a photo of an archaeological find',
        addFirst: 'Add First Discovery',
        
        // New Discovery
        uploadPhoto: 'Upload Photo',
        analyzeWithAI: 'Analyze with AI',
        analyzing: 'Analyzing...',
        scanning: 'Scanning...',
        researching: 'Researching...',
        translating: 'Translating...',
        uploadingImages: 'Uploading images...',
        step1: 'Step 1',
        step2: 'Step 2',
        step3: 'Step 3',
        optionalDetails: 'Optional details',
        helpsAI: 'helps AI identify more accurately',
        markLocation: 'Mark Discovery Location',
        clickMap: 'Click on the map to mark where you found this object',
        addDetails: 'Add Details',
        discoveryName: 'Discovery Name',
        locationName: 'Location Name',
        discoveryDate: 'Discovery Date',
        notes: 'Notes',
        saveDiscovery: 'Save Discovery',
        back: 'Back',
        continue: 'Continue',
        advancedMode: 'Advanced Mode',
        depthFound: 'Depth Found',
        soilType: 'Soil Type',
        condition: 'Condition',
        detectionMethod: 'Detection Method',
        additionalPhotos: 'Additional Photos',
        
        // Analysis
        aiAnalysis: 'AI Analysis Results',
        period: 'Period',
        origin: 'Origin',
        material: 'Material',
        confidence: 'confidence',
        similarFinds: 'Similar Finds',
        howToStore: 'How to Store',
        databaseReferences: 'Database References',
        
        // Discovery Detail
        share: 'Share',
        reportToGov: 'Report to Government',
        foundBy: 'Found by',
        foundOn: 'Found on',
        private: 'Private',
        makePrivate: 'Make Private',
        makePublic: 'Make Public',
        
        // Settings
        appearance: 'Appearance',
        darkMode: 'Dark Mode',
        language: 'Language',
        selectLanguage: 'Select your language',
        toggleTheme: 'Toggle between light and dark mode',
        notifications: 'Notifications',
        emailNotifications: 'Email Notifications',
        account: 'Account',
        signOut: 'Sign Out',
        signIn: 'Sign In',
        loginRequired: 'Login Required',
        loginToAccess: 'Please login to access this feature',
        
        // Statistics
        statisticsTitle: 'Statistics & Achievements',
        trackYourDiscoveries: 'Track your archaeological discoveries and achievements',
        thisMonth: 'This Month',
        timeline: 'Discovery Timeline',
        rarityDistribution: 'Rarity Distribution',
        noDataYet: 'No data yet',
        
        // Filters
        search: 'Search',
        filterByStatus: 'Filter by status',
        allStatus: 'All Status',
        pendingAnalysis: 'Pending Analysis',
        verified: 'Verified',
        reported: 'Reported',
        
        // Share
        shareDiscovery: 'Share Discovery',
        copyLink: 'Copy Link',
        copied: 'Copied!',
        shareVia: 'Share via',
        
        // Auth
        welcomeBack: 'Welcome Back',
        loginToContinue: 'Login to continue to Archeos',
        loginWithGoogle: 'Continue with Google',
        loginWithMicrosoft: 'Continue with Microsoft',
        orContinueWith: 'Or continue with',
        email: 'Email',
        password: 'Password',
        login: 'Login',
        noAccount: "Don't have an account?",
        createAccount: 'Create Account',
        continueAsGuest: 'Continue as Guest',
        guestLimitations: 'Some features will be limited',
        catAll: 'All',
        catCoins: 'Coins',
        catPipes: 'Pipes',
        catJewelry: 'Jewelry',
        catWeapons: 'Weapons',
        catTools: 'Tools',
        catPottery: 'Pottery',
        catOther: 'Other',
        
        // Admin
        accessDenied: 'Access Denied',
        adminAccessRequired: 'Administrator access required.',
        adminPanel: 'Admin Panel',
        users: 'Users',
        user: 'User',
        actions: 'Actions',
        allStatuses: 'All Statuses',
        discovery: 'Discovery',
        finder: 'Finder',
        status: 'Status',
        date: 'Date',
        editDiscovery: 'Edit Discovery',
        name: 'Name',
        finderName: 'Finder Name',
        visibility: 'Visibility',
        public: 'Public',
        cancel: 'Cancel',
        save: 'Save',
        deleteDiscovery: 'Delete Discovery?',
        cannotBeUndone: 'This cannot be undone.',
        delete: 'Delete',
        searchDiscoveries: 'Search discoveries...',
        
        // Admin Experts
        expertsCount: 'experts',
        addExpert: 'Add Expert',
        specialization: 'Specialization',
        institution: 'Institution',
        editExpert: 'Edit Expert',
        nameRequired: 'Name *',
        specializationRequired: 'Specialization *',
        emailRequired: 'Email *',
        phone: 'Phone',
        location: 'Location',
        imageUrl: 'Image URL',
        bio: 'Bio',
        available: 'Available',
        unavailable: 'Unavailable',
        pinned: 'Pinned (shows at top)',
        deleteExpert: 'Delete Expert?',
        
        // Admin Reports
        reference: 'Reference',
        
        // Admin Users
        searchUsers: 'Search users...',
        role: 'Role',
        joined: 'Joined',
        changeRole: 'Change Role',
        unknown: 'Unknown',
        
        // Discoveries page
        fromAllUsers: 'from all users',
        
        // Government Report
        reportToGovernmentFull: 'Report to Government',
        reportToRCE: 'Report your find to Rijksdienst voor het Cultureel Erfgoed (RCE)',
        reportSaved: 'Report saved! Now open the government form and copy each value below. Click any value to copy it.',
        valuesToFill: 'Values to fill in on the government form',
        openForm: 'Open Form',
        notAvailable: '— not available —',
        coordinateNote: '⚠️ Note: The X and Y coordinates are in decimal degrees (WGS84). The form uses RD New (Rijksdriehoek) — you may need to convert them. Use epsg.io/transform to convert. Also don\'t forget to upload photos of the front, back, and side.',
        doneGoToReports: 'Done — Go to Reports',
        selectDiscoveryToReport: 'Select which discovery you want to report. We\'ll check if all required information is available and help you fill in the government form.',
        noDiscoveriesYet: 'You have no discoveries yet. Add one first.',
        noLocation: 'No location',
        noDate: 'No date',
        alreadyReported: 'Already reported',
        reviewCheckInfo: 'Review & Check Information',
        infoCheckFor: 'Information check for:',
        missingInfo: 'Some information is missing',
        fillMissingFields: 'Please fill in the missing fields below so the government form can be completed properly.',
        noCoordinates: '⚠️ No location coordinates found',
        goBackAddLocation: 'Go back to this discovery and add a map location.',
        toponiem: 'Toponiem *',
        toponiemHint: '(field/street/water name where found)',
        toponiemPlaceholder: 'e.g. Binnenveld, Maas, Dorpsstraat',
        detectionMethodLabel: 'Detection method (Vondstverwerving) *',
        selectOption: 'Select...',
        metalDetector: 'Metal detector',
        digging: 'Digging (graafwerk)',
        surfaceFind: 'Surface find (kartering)',
        dredging: 'Dredging (baggerwerk)',
        borehole: 'Borehole (boring)',
        diving: 'Diving',
        conditionLabel: 'Condition (Toestand) *',
        complete: 'Complete',
        fragment: 'Fragment',
        notApplicable: 'N/A',
        materialLabel: 'Material (Materiaal) *',
        materialPlaceholder: 'e.g. Bronze, Silver, Clay...',
        descriptionNotes: 'Description / notes (Toelichting) *',
        descriptionPlaceholder: 'Describe the find in more detail: dimensions, markings, condition details, etc.',
        additionalDetails: 'Additional details',
        optional: '(optional but helpful)',
        plaats: 'Plaats',
        plaatsHint: '(nearest city/town)',
        plaatsPlaceholder: 'e.g. Utrecht, Amsterdam',
        aantal: 'Aantal',
        aantalHint: '(number of finds)',
        currentStorage: 'Current storage',
        currentStorageHint: '(where is the find now?)',
        currentStoragePlaceholder: 'e.g. At home, in a box',
        extraNotes: 'Extra notes for toelichting',
        extraNotesPlaceholder: 'Any extra details about the find...',
        whenYouClick: 'When you click "Open Government Form", we\'ll open the official RCE form with all your information pre-filled. You may still need to upload photos and check the coordinate format manually.',
        continueToChecklist: 'Continue to Copy Checklist',
        
        // Reports page
        newReport: 'New Report',
        pending: 'Pending',
        deleteReport: 'Delete report?',
        deleteReportWarning: 'This will delete the report and mark the discovery as "not yet reported". This cannot be undone.',
        view: 'View',
        
        // Share Dialog
        archeos: 'ArcheOS',
        whatsapp: 'WhatsApp',
        xTwitter: 'X',
        facebook: 'Facebook',
        more: 'More',
        
        // Discovery Map
        searchLocation: 'Zoek een locatie...',
        unknownObject: 'Unknown Object',
        locationNotSpecified: 'Location not specified',
    },
    nl: {
        home: 'Home',
        discoveries: 'Vondsten',
        myDiscoveries: 'Mijn Vondsten',
        community: 'Gemeenschap',
        map: 'Kaart',
        experts: 'Experts',
        reports: 'Rapporten',
        statistics: 'Statistieken',
        settings: 'Instellingen',
        admin: 'Admin',
        welcome: 'Archeos',
        tagline: 'Ontdek, identificeer en documenteer archeologische vondsten met AI-analyse',
        newDiscovery: 'Nieuwe Vondst',
        viewMap: 'Bekijk Kaart',
        contactExpert: 'Expert Contacteren',
        totalDiscoveries: 'Totaal Vondsten',
        identified: 'Geïdentificeerd',
        reportsFiled: 'Rapporten',
        recentDiscoveries: 'Recente Vondsten',
        viewAll: 'Bekijk Alle',
        noDiscoveries: 'Nog geen vondsten',
        startBy: 'Begin met het uploaden van een foto',
        addFirst: 'Eerste Vondst Toevoegen',
        uploadPhoto: 'Foto Uploaden',
        analyzeWithAI: 'Analyseren met AI',
        analyzing: 'Analyseren...',
        scanning: 'Scannen...',
        researching: 'Onderzoeken...',
        uploadingImages: 'Afbeeldingen uploaden...',
        helpsAI: 'helpt AI nauwkeuriger identificeren',
        markLocation: 'Markeer Vindplaats',
        clickMap: 'Klik op de kaart om aan te geven waar je dit object hebt gevonden',
        addDetails: 'Details Toevoegen',
        discoveryName: 'Naam Vondst',
        locationName: 'Locatie Naam',
        discoveryDate: 'Datum Vondst',
        notes: 'Notities',
        saveDiscovery: 'Vondst Opslaan',
        back: 'Terug',
        continue: 'Doorgaan',
        advancedMode: 'Geavanceerde Modus',
        depthFound: 'Diepte Gevonden',
        soilType: 'Grondsoort',
        condition: 'Conditie',
        detectionMethod: 'Detectie Methode',
        additionalPhotos: 'Extra Foto\'s',
        aiAnalysis: 'AI Analyse Resultaten',
        period: 'Periode',
        origin: 'Herkomst',
        material: 'Materiaal',
        confidence: 'zekerheid',
        similarFinds: 'Vergelijkbare Vondsten',
        howToStore: 'Opslaginstructies',
        databaseReferences: 'Database Referenties',
        share: 'Delen',
        reportToGov: 'Melden bij Overheid',
        foundBy: 'Gevonden door',
        foundOn: 'Gevonden op',
        private: 'Privé',
        makePrivate: 'Maak Privé',
        makePublic: 'Maak Openbaar',
        appearance: 'Uiterlijk',
        darkMode: 'Donkere Modus',
        language: 'Taal',
        selectLanguage: 'Selecteer uw taal',
        toggleTheme: 'Schakel tussen licht en donker',
        notifications: 'Meldingen',
        emailNotifications: 'E-mailmeldingen',
        account: 'Account',
        signOut: 'Uitloggen',
        signIn: 'Inloggen',
        loginRequired: 'Inloggen Vereist',
        loginToAccess: 'Log in om deze functie te gebruiken',
        statisticsTitle: 'Statistieken & Prestaties',
        trackYourDiscoveries: 'Volg je archeologische vondsten en prestaties',
        thisMonth: 'Deze Maand',
        timeline: 'Vondsten Tijdlijn',
        rarityDistribution: 'Zeldzaamheid Verdeling',
        noDataYet: 'Nog geen gegevens',
        search: 'Zoeken',
        filterByStatus: 'Filter op status',
        allStatus: 'Alle Status',
        pendingAnalysis: 'Wacht op Analyse',
        verified: 'Geverifieerd',
        reported: 'Gemeld',
        shareDiscovery: 'Vondst Delen',
        copyLink: 'Link Kopiëren',
        copied: 'Gekopieerd!',
        shareVia: 'Delen via',
        welcomeBack: 'Welkom Terug',
        loginToContinue: 'Log in om door te gaan naar Archeos',
        loginWithGoogle: 'Doorgaan met Google',
        loginWithMicrosoft: 'Doorgaan met Microsoft',
        orContinueWith: 'Of ga verder met',
        email: 'E-mail',
        password: 'Wachtwoord',
        login: 'Inloggen',
        noAccount: 'Nog geen account?',
        createAccount: 'Account Aanmaken',
        continueAsGuest: 'Doorgaan als Gast',
        guestLimitations: 'Sommige functies zijn beperkt',
        catAll: 'Alle',
        catCoins: 'Munten',
        catPipes: 'Pijpen',
        catJewelry: 'Sieraden',
        catWeapons: 'Wapens',
        catTools: 'Gereedschap',
        catPottery: 'Aardewerk',
        catOther: 'Overig',
        
        // Admin
        accessDenied: 'Toegang Geweigerd',
        adminAccessRequired: 'Beheerderstoegang vereist.',
        adminPanel: 'Beheerpaneel',
        users: 'Gebruikers',
        user: 'Gebruiker',
        actions: 'Acties',
        allStatuses: 'Alle Statussen',
        discovery: 'Vondst',
        finder: 'Vinder',
        status: 'Status',
        date: 'Datum',
        editDiscovery: 'Vondst Bewerken',
        name: 'Naam',
        finderName: 'Naam Vinder',
        visibility: 'Zichtbaarheid',
        public: 'Openbaar',
        cancel: 'Annuleren',
        save: 'Opslaan',
        deleteDiscovery: 'Vondst Verwijderen?',
        cannotBeUndone: 'Dit kan niet ongedaan worden gemaakt.',
        delete: 'Verwijderen',
        searchDiscoveries: 'Vondsten zoeken...',
        
        // Admin Experts
        expertsCount: 'experts',
        addExpert: 'Expert Toevoegen',
        specialization: 'Specialisatie',
        institution: 'Instelling',
        editExpert: 'Expert Bewerken',
        nameRequired: 'Naam *',
        specializationRequired: 'Specialisatie *',
        emailRequired: 'E-mail *',
        phone: 'Telefoon',
        location: 'Locatie',
        imageUrl: 'Afbeelding URL',
        bio: 'Bio',
        available: 'Beschikbaar',
        unavailable: 'Niet beschikbaar',
        pinned: 'Vastgepind (bovenaan weergeven)',
        deleteExpert: 'Expert Verwijderen?',
        
        // Admin Reports
        reference: 'Referentie',
        
        // Admin Users
        searchUsers: 'Gebruikers zoeken...',
        role: 'Rol',
        joined: 'Toegetreden',
        changeRole: 'Rol Wijzigen',
        unknown: 'Onbekend',
        
        // Discoveries page
        fromAllUsers: 'van alle gebruikers',
        
        // Government Report
        reportToGovernmentFull: 'Melden bij Overheid',
        reportToRCE: 'Meld je vondst bij Rijksdienst voor het Cultureel Erfgoed (RCE)',
        reportSaved: 'Rapport opgeslagen! Open nu het overheidsformulier en kopieer elke waarde hieronder. Klik op een waarde om te kopiëren.',
        valuesToFill: 'Waarden om in te vullen op het overheidsformulier',
        openForm: 'Formulier Openen',
        notAvailable: '— niet beschikbaar —',
        coordinateNote: '⚠️ Let op: De X en Y coördinaten zijn in decimale graden (WGS84). Het formulier gebruikt RD Nieuw (Rijksdriehoek) — mogelijk moet je ze converteren. Gebruik epsg.io/transform om te converteren. Vergeet ook niet om foto\'s van voor-, achter- en zijkant te uploaden.',
        doneGoToReports: 'Klaar — Ga naar Rapporten',
        selectDiscoveryToReport: 'Selecteer welke vondst je wilt melden. We controleren of alle benodigde informatie beschikbaar is en helpen je met het invullen van het overheidsformulier.',
        noDiscoveriesYet: 'Je hebt nog geen vondsten. Voeg er eerst een toe.',
        noLocation: 'Geen locatie',
        noDate: 'Geen datum',
        alreadyReported: 'Reeds gemeld',
        reviewCheckInfo: 'Controleren & Informatie Nakijken',
        infoCheckFor: 'Informatiecontrole voor:',
        missingInfo: 'Sommige informatie ontbreekt',
        fillMissingFields: 'Vul de onderstaande ontbrekende velden in zodat het overheidsformulier correct kan worden voltooid.',
        noCoordinates: '⚠️ Geen locatiecoördinaten gevonden',
        goBackAddLocation: 'Ga terug naar deze vondst en voeg een locatie op de kaart toe.',
        toponiem: 'Toponiem *',
        toponiemHint: '(veld/straat/waternaam waar gevonden)',
        toponiemPlaceholder: 'bijv. Binnenveld, Maas, Dorpsstraat',
        detectionMethodLabel: 'Detectiemethode (Vondstverwerving) *',
        selectOption: 'Selecteer...',
        metalDetector: 'Metaaldetector',
        digging: 'Graafwerk',
        surfaceFind: 'Oppervlaktevondst (kartering)',
        dredging: 'Baggerwerk',
        borehole: 'Boring',
        diving: 'Duikactiviteiten',
        conditionLabel: 'Toestand *',
        complete: 'Compleet',
        fragment: 'Fragment',
        notApplicable: 'N.v.t.',
        materialLabel: 'Materiaal *',
        materialPlaceholder: 'bijv. Brons, Zilver, Klei...',
        descriptionNotes: 'Beschrijving / notities (Toelichting) *',
        descriptionPlaceholder: 'Beschrijf de vondst in meer detail: afmetingen, markeringen, conditiedetails, etc.',
        additionalDetails: 'Extra details',
        optional: '(optioneel maar nuttig)',
        plaats: 'Plaats',
        plaatsHint: '(dichtstbijzijnde stad/dorp)',
        plaatsPlaceholder: 'bijv. Utrecht, Amsterdam',
        aantal: 'Aantal',
        aantalHint: '(aantal vondsten)',
        currentStorage: 'Huidige opslag',
        currentStorageHint: '(waar is de vondst nu?)',
        currentStoragePlaceholder: 'bijv. Thuis, in een doos',
        extraNotes: 'Extra notities voor toelichting',
        extraNotesPlaceholder: 'Extra details over de vondst...',
        whenYouClick: 'Wanneer je op "Formulier Openen" klikt, openen we het officiële RCE-formulier met al je informatie vooraf ingevuld. Je moet mogelijk nog steeds foto\'s uploaden en het coördinatenformaat handmatig controleren.',
        continueToChecklist: 'Doorgaan naar Kopieerlijst',
        
        // Reports page
        newReport: 'Nieuw Rapport',
        pending: 'In behandeling',
        deleteReport: 'Rapport verwijderen?',
        deleteReportWarning: 'Dit verwijdert het rapport en markeert de vondst als "nog niet gemeld". Dit kan niet ongedaan worden gemaakt.',
        view: 'Bekijken',
        
        // Share Dialog
        archeos: 'ArcheOS',
        whatsapp: 'WhatsApp',
        xTwitter: 'X',
        facebook: 'Facebook',
        more: 'Meer',
        
        // Discovery Map
        searchLocation: 'Zoek een locatie...',
        unknownObject: 'Onbekend Object',
        locationNotSpecified: 'Locatie niet gespecificeerd',
        
        // Additional new translations (unique keys only)
        unknownLocation: 'Onbekende locatie',
        step1: 'Stap 1',
        step2: 'Stap 2',
        step3: 'Stap 3',
        optionalDetails: 'Optionele details',
        optionalDetailsHint: '— helpt AI nauwkeuriger identificeren',
        selectPlaceholder: 'Selecteren...',
        depthSurface: 'Oppervlakte (0-5cm)',
        depthShallow: 'Ondiep (5-15cm)',
        depthMedium: 'Middel (15-30cm)',
        depthDeep: 'Diep (30cm+)',
        soilSandy: 'Zand',
        soilClay: 'Klei',
        soilLoam: 'Leem',
        soilPeat: 'Veen',
        conditionExcellent: 'Uitstekend',
        conditionGood: 'Goed',
        conditionFair: 'Redelijk',
        conditionPoor: 'Slecht',
        conditionFragmentary: 'Fragmentarisch',
        detectionMetalDetector: 'Metaaldetector',
        detectionDigging: 'Graven',
        detectionSurfaceFind: 'Oppervlaktevondst',
        detectionConstruction: 'Bouwwerk',
        detectionOther: 'Overig',
        usefulReferences: 'Nuttige referenties voor je vondst:',
        guestWarning: 'Je bent een gast',
        guestWarningText: 'Je vondst wordt openbaar gemaakt. Log in om privaat te blijven.',
        aiFailed: 'AI-analyse mislukt. Probeer het opnieuw.',
        notArchaeological: 'Geen archeologisch object',
        notArchaeologicalText: 'De AI heeft vastgesteld dat dit waarschijnlijk geen archeologisch object is.',
        notArchaeologicalReason: 'Geef aan waarom je denkt dat dit wel een archeologisch object is...',
        submitAppeal: 'Bezwaar indienen bij team ArcheOS',
        appealSubmitted: 'Bezwaar ingediend — team ArcheOS bekijkt dit.',
        appealApproved: 'Bezwaar goedgekeurd — vondst is nu zichtbaar in de community.',
        approveAppeal: 'Bezwaar goedkeuren (Admin)',
        selectedCoordinates: 'Geselecteerd: {lat}, {lng}',
        noImage: 'Geen afbeelding',
        discoveryLocation: 'Vondst Locatie',
        adminActions: 'Admin Acties',
        deleteDiscoveryConfirm: 'Weet je het zeker? Dit kan niet ongedaan worden.',
        selectExpert: 'Expert Selecteren',
        chooseExpert: 'Kies een expert...',
        openInEmail: 'Open in Email App',
        foundByLabel: 'Gevonden door',
        panDatabase: 'PAN Database',
        rceBeeldbank: 'RCE Beeldbank',
        saveAndReport: 'Opslaan & Direct Melden',
        coins: 'Munten',
        pipes: 'Pijpen',
        jewelry: 'Sieraden',
        weapons: 'Wapens',
        tools: 'Gereedschap',
        pottery: 'Aardewerk',
        allMaterials: 'Alle Materialen',
        allPeriods: 'Alle Periodes',
        allRarities: 'Alle Zeldzaamheden',
        bronze: 'Brons',
        silver: 'Zilver',
        gold: 'Goud',
        ceramic: 'Keramiek',
        stone: 'Steen',
        iron: 'IJzer',
        roman: 'Romeins',
        medieval: 'Middeleeuws',
        bronzeAge: 'Bronstijd',
        ironAge: 'IJzertijd',
        neolithic: 'Neolithicum',
        common: 'Gewoon',
        uncommon: 'Ongewoon',
        rare: 'Zeldzaam',
        veryRare: 'Zeer Zeldzaam',
        legendary: 'Legendarisch',
        yourDiscoveriesOnMap: 'Je vondsten op de kaart',
        analytics: 'Analyses',
        credits: 'Credits',
        totalDiscoveriesAdmin: 'Totaal Vondsten',
        verifiedAdmin: 'Geverifieerd',
        pendingAdmin: 'In Afwachting',
        consultationRequest: 'Archeologische Consultatie Aanvraag',
        message: 'Bericht',
        messagePlaceholder: 'Schrijf je bericht hier...',
    },
    de: {
        home: 'Startseite',
        discoveries: 'Entdeckungen',
        myDiscoveries: 'Meine Entdeckungen',
        community: 'Gemeinschaft',
        map: 'Karte',
        experts: 'Experten',
        reports: 'Berichte',
        statistics: 'Statistiken',
        settings: 'Einstellungen',
        admin: 'Admin',
        editLabel: 'Label bearbeiten',
        editTimeLabel: 'Zeitlabel bearbeiten',
        useMyLocation: 'Meinen Standort Verwenden',
        geoNotSupported: 'Geolokalisierung wird von Ihrem Browser nicht unterstützt',
        geoError: 'Ihr Standort konnte nicht abgerufen werden',
        welcome: 'Archeos',
        tagline: 'Entdecken, identifizieren und dokumentieren Sie archäologische Funde mit KI-Analyse',
        newDiscovery: 'Neue Entdeckung',
        viewMap: 'Karte Ansehen',
        contactExpert: 'Experte Kontaktieren',
        totalDiscoveries: 'Gesamtfunde',
        identified: 'Identifiziert',
        reportsFiled: 'Berichte',
        recentDiscoveries: 'Neueste Funde',
        viewAll: 'Alle Ansehen',
        noDiscoveries: 'Noch keine Funde',
        startBy: 'Laden Sie ein Foto hoch',
        addFirst: 'Ersten Fund Hinzufügen',
        uploadPhoto: 'Foto Hochladen',
        analyzeWithAI: 'Mit KI Analysieren',
        analyzing: 'Analysieren...',
        scanning: 'Scannen...',
        researching: 'Recherchieren...',
        uploadingImages: 'Bilder hochladen...',
        helpsAI: 'hilft KI genauer zu identifizieren',
        markLocation: 'Fundort Markieren',
        clickMap: 'Klicken Sie auf die Karte, um anzuzeigen, wo Sie dieses Objekt gefunden haben',
        addDetails: 'Details Hinzufügen',
        discoveryName: 'Name des Fundes',
        locationName: 'Ortsname',
        discoveryDate: 'Funddatum',
        notes: 'Notizen',
        saveDiscovery: 'Fund Speichern',
        back: 'Zurück',
        continue: 'Weiter',
        advancedMode: 'Erweiterter Modus',
        depthFound: 'Fundtiefe',
        soilType: 'Bodenart',
        condition: 'Zustand',
        detectionMethod: 'Detektionsmethode',
        additionalPhotos: 'Zusätzliche Fotos',
        aiAnalysis: 'KI-Analyseergebnisse',
        period: 'Zeitraum',
        origin: 'Herkunft',
        material: 'Material',
        confidence: 'Sicherheit',
        similarFinds: 'Ähnliche Funde',
        howToStore: 'Lagerungshinweise',
        databaseReferences: 'Datenbank-Referenzen',
        share: 'Teilen',
        reportToGov: 'An Behörde Melden',
        foundBy: 'Gefunden von',
        foundOn: 'Gefunden am',
        private: 'Privat',
        makePrivate: 'Privat Machen',
        makePublic: 'Öffentlich Machen',
        appearance: 'Erscheinung',
        darkMode: 'Dunkelmodus',
        language: 'Sprache',
        selectLanguage: 'Wählen Sie Ihre Sprache',
        toggleTheme: 'Zwischen hell und dunkel wechseln',
        notifications: 'Benachrichtigungen',
        emailNotifications: 'E-Mail-Benachrichtigungen',
        account: 'Konto',
        signOut: 'Abmelden',
        signIn: 'Anmelden',
        loginRequired: 'Anmeldung Erforderlich',
        loginToAccess: 'Bitte melden Sie sich an, um diese Funktion zu nutzen',
        statisticsTitle: 'Statistiken & Erfolge',
        trackYourDiscoveries: 'Verfolgen Sie Ihre archäologischen Funde und Erfolge',
        thisMonth: 'Diesen Monat',
        timeline: 'Fund-Zeitachse',
        rarityDistribution: 'Seltenheitsverteilung',
        noDataYet: 'Noch keine Daten',
        search: 'Suchen',
        filterByStatus: 'Nach Status filtern',
        allStatus: 'Alle Status',
        pendingAnalysis: 'Warten auf Analyse',
        verified: 'Verifiziert',
        reported: 'Gemeldet',
        shareDiscovery: 'Fund Teilen',
        copyLink: 'Link Kopieren',
        copied: 'Kopiert!',
        shareVia: 'Teilen über',
        welcomeBack: 'Willkommen Zurück',
        loginToContinue: 'Melden Sie sich an, um zu Archeos fortzufahren',
        loginWithGoogle: 'Mit Google Fortfahren',
        loginWithMicrosoft: 'Mit Microsoft Fortfahren',
        orContinueWith: 'Oder fahren Sie fort mit',
        email: 'E-Mail',
        password: 'Passwort',
        login: 'Anmelden',
        noAccount: 'Noch kein Konto?',
        createAccount: 'Konto Erstellen',
        continueAsGuest: 'Als Gast Fortfahren',
        guestLimitations: 'Einige Funktionen werden eingeschränkt sein',
        catAll: 'Alle',
        catCoins: 'Münzen',
        catPipes: 'Pfeifen',
        catJewelry: 'Schmuck',
        catWeapons: 'Waffen',
        catTools: 'Werkzeug',
        catPottery: 'Keramik',
        catOther: 'Sonstiges',
        
        // Admin
        accessDenied: 'Zugriff Verweigert',
        adminAccessRequired: 'Administratorzugriff erforderlich.',
        adminPanel: 'Admin-Panel',
        users: 'Benutzer',
        user: 'Benutzer',
        actions: 'Aktionen',
        allStatuses: 'Alle Status',
        discovery: 'Fund',
        finder: 'Finder',
        status: 'Status',
        date: 'Datum',
        editDiscovery: 'Fund Bearbeiten',
        name: 'Name',
        finderName: 'Name des Finders',
        visibility: 'Sichtbarkeit',
        public: 'Öffentlich',
        cancel: 'Abbrechen',
        save: 'Speichern',
        deleteDiscovery: 'Fund Löschen?',
        cannotBeUndone: 'Dies kann nicht rückgängig gemacht werden.',
        delete: 'Löschen',
        searchDiscoveries: 'Funde suchen...',
        
        // Admin Experts
        expertsCount: 'Experten',
        addExpert: 'Experte Hinzufügen',
        specialization: 'Spezialisierung',
        institution: 'Institution',
        editExpert: 'Experte Bearbeiten',
        nameRequired: 'Name *',
        specializationRequired: 'Spezialisierung *',
        emailRequired: 'E-Mail *',
        phone: 'Telefon',
        location: 'Standort',
        imageUrl: 'Bild-URL',
        bio: 'Biografie',
        available: 'Verfügbar',
        unavailable: 'Nicht verfügbar',
        pinned: 'Angepinnt (oben anzeigen)',
        deleteExpert: 'Experte Löschen?',
        
        // Admin Reports
        reference: 'Referenz',
        
        // Admin Users
        searchUsers: 'Benutzer suchen...',
        role: 'Rolle',
        joined: 'Beigetreten',
        changeRole: 'Rolle Ändern',
        unknown: 'Unbekannt',
        
        // Discoveries page
        fromAllUsers: 'von allen Benutzern',
        
        // Government Report
        reportToGovernmentFull: 'An Behörde Melden',
        reportToRCE: 'Melden Sie Ihren Fund an Rijksdienst voor het Cultureel Erfgoed (RCE)',
        reportSaved: 'Bericht gespeichert! Öffnen Sie jetzt das Behördenformular und kopieren Sie jeden Wert unten. Klicken Sie auf einen Wert zum Kopieren.',
        valuesToFill: 'Werte zum Ausfüllen im Behördenformular',
        openForm: 'Formular Öffnen',
        notAvailable: '— nicht verfügbar —',
        coordinateNote: '⚠️ Hinweis: Die X- und Y-Koordinaten sind in Dezimalgrad (WGS84). Das Formular verwendet RD New (Rijksdriehoek) — möglicherweise müssen Sie sie konvertieren. Verwenden Sie epsg.io/transform zum Konvertieren. Vergessen Sie auch nicht, Fotos von Vorder-, Rück- und Seitenansicht hochzuladen.',
        doneGoToReports: 'Fertig — Zu Berichten Gehen',
        selectDiscoveryToReport: 'Wählen Sie aus, welchen Fund Sie melden möchten. Wir prüfen, ob alle erforderlichen Informationen verfügbar sind und helfen Ihnen beim Ausfüllen des Behördenformulars.',
        noDiscoveriesYet: 'Sie haben noch keine Funde. Fügen Sie zuerst einen hinzu.',
        noLocation: 'Kein Standort',
        noDate: 'Kein Datum',
        alreadyReported: 'Bereits gemeldet',
        reviewCheckInfo: 'Überprüfen & Informationen Prüfen',
        infoCheckFor: 'Informationsprüfung für:',
        missingInfo: 'Einige Informationen fehlen',
        fillMissingFields: 'Bitte füllen Sie die fehlenden Felder unten aus, damit das Behördenformular korrekt ausgefüllt werden kann.',
        noCoordinates: '⚠️ Keine Standortkoordinaten gefunden',
        goBackAddLocation: 'Gehen Sie zurück zu diesem Fund und fügen Sie einen Kartenstandort hinzu.',
        toponiem: 'Toponiem *',
        toponiemHint: '(Feld-/Straßen-/Wassername, wo gefunden)',
        toponiemPlaceholder: 'z.B. Binnenveld, Maas, Dorpsstraat',
        detectionMethodLabel: 'Detektionsmethode (Vondstverwerving) *',
        selectOption: 'Auswählen...',
        metalDetector: 'Metalldetektor',
        digging: 'Graben (graafwerk)',
        surfaceFind: 'Oberflächenfund (kartering)',
        dredging: 'Baggern (baggerwerk)',
        borehole: 'Bohrloch (boring)',
        diving: 'Tauchen',
        conditionLabel: 'Zustand (Toestand) *',
        complete: 'Vollständig',
        fragment: 'Fragment',
        notApplicable: 'N/A',
        materialLabel: 'Material (Materiaal) *',
        materialPlaceholder: 'z.B. Bronze, Silber, Ton...',
        descriptionNotes: 'Beschreibung / Notizen (Toelichting) *',
        descriptionPlaceholder: 'Beschreiben Sie den Fund detaillierter: Abmessungen, Markierungen, Zustandsdetails usw.',
        additionalDetails: 'Zusätzliche Details',
        optional: '(optional aber hilfreich)',
        plaats: 'Plaats',
        plaatsHint: '(nächste Stadt/Dorf)',
        plaatsPlaceholder: 'z.B. Utrecht, Amsterdam',
        aantal: 'Aantal',
        aantalHint: '(Anzahl der Funde)',
        currentStorage: 'Aktuelle Lagerung',
        currentStorageHint: '(wo ist der Fund jetzt?)',
        currentStoragePlaceholder: 'z.B. Zu Hause, in einer Box',
        extraNotes: 'Zusätzliche Notizen für Toelichting',
        extraNotesPlaceholder: 'Weitere Details zum Fund...',
        whenYouClick: 'Wenn Sie auf "Formular Öffnen" klicken, öffnen wir das offizielle RCE-Formular mit allen Ihren vorausgefüllten Informationen. Möglicherweise müssen Sie noch Fotos hochladen und das Koordinatenformat manuell überprüfen.',
        continueToChecklist: 'Weiter zur Kopierliste',
        
        // Reports page
        newReport: 'Neuer Bericht',
        pending: 'Ausstehend',
        deleteReport: 'Bericht löschen?',
        deleteReportWarning: 'Dies löscht den Bericht und markiert den Fund als "noch nicht gemeldet". Dies kann nicht rückgängig gemacht werden.',
        view: 'Ansehen',
        
        // Share Dialog
        archeos: 'ArcheOS',
        whatsapp: 'WhatsApp',
        xTwitter: 'X',
        facebook: 'Facebook',
        more: 'Mehr',
        
        // Discovery Map
        searchLocation: 'Standort suchen...',
        unknownObject: 'Unbekanntes Objekt',
        locationNotSpecified: 'Standort nicht angegeben',
    },
    fr: {
        home: 'Accueil',
        discoveries: 'Découvertes',
        myDiscoveries: 'Mes Découvertes',
        community: 'Communauté',
        map: 'Carte',
        experts: 'Experts',
        reports: 'Rapports',
        statistics: 'Statistiques',
        settings: 'Paramètres',
        admin: 'Admin',
        editLabel: 'Modifier l\'étiquette',
        editTimeLabel: 'Modifier l\'étiquette temporelle',
        useMyLocation: 'Utiliser Ma Position',
        geoNotSupported: 'La géolocalisation n\'est pas prise en charge par votre navigateur',
        geoError: 'Impossible de récupérer votre position',
        welcome: 'Archeos',
        tagline: 'Découvrez, identifiez et documentez les trouvailles archéologiques avec l\'analyse IA',
        newDiscovery: 'Nouvelle Découverte',
        viewMap: 'Voir la Carte',
        contactExpert: 'Contacter Expert',
        totalDiscoveries: 'Total Découvertes',
        identified: 'Identifiées',
        reportsFiled: 'Rapports',
        recentDiscoveries: 'Découvertes Récentes',
        viewAll: 'Voir Tout',
        noDiscoveries: 'Aucune découverte',
        startBy: 'Commencez par télécharger une photo',
        addFirst: 'Ajouter Première Découverte',
        uploadPhoto: 'Télécharger Photo',
        analyzeWithAI: 'Analyser avec IA',
        analyzing: 'Analyse en cours...',
        scanning: 'Analyse...',
        researching: 'Recherche...',
        uploadingImages: 'Téléchargement des images...',
        helpsAI: 'aide l\'IA à identifier plus précisément',
        markLocation: 'Marquer l\'Emplacement',
        clickMap: 'Cliquez sur la carte pour indiquer où vous avez trouvé cet objet',
        addDetails: 'Ajouter Détails',
        discoveryName: 'Nom de la Découverte',
        locationName: 'Nom du Lieu',
        discoveryDate: 'Date de Découverte',
        notes: 'Notes',
        saveDiscovery: 'Enregistrer Découverte',
        back: 'Retour',
        continue: 'Continuer',
        advancedMode: 'Mode Avancé',
        depthFound: 'Profondeur Trouvée',
        soilType: 'Type de Sol',
        condition: 'Condition',
        detectionMethod: 'Méthode de Détection',
        additionalPhotos: 'Photos Supplémentaires',
        aiAnalysis: 'Résultats de l\'Analyse IA',
        period: 'Période',
        origin: 'Origine',
        material: 'Matériau',
        confidence: 'confiance',
        similarFinds: 'Trouvailles Similaires',
        howToStore: 'Comment Stocker',
        databaseReferences: 'Références Base de Données',
        share: 'Partager',
        reportToGov: 'Signaler au Gouvernement',
        foundBy: 'Trouvé par',
        foundOn: 'Trouvé le',
        private: 'Privé',
        makePrivate: 'Rendre Privé',
        makePublic: 'Rendre Public',
        appearance: 'Apparence',
        darkMode: 'Mode Sombre',
        language: 'Langue',
        selectLanguage: 'Sélectionnez votre langue',
        toggleTheme: 'Basculer entre clair et sombre',
        notifications: 'Notifications',
        emailNotifications: 'Notifications par E-mail',
        account: 'Compte',
        signOut: 'Se Déconnecter',
        signIn: 'Se Connecter',
        loginRequired: 'Connexion Requise',
        loginToAccess: 'Veuillez vous connecter pour accéder à cette fonctionnalité',
        statisticsTitle: 'Statistiques & Réalisations',
        trackYourDiscoveries: 'Suivez vos découvertes archéologiques et vos réalisations',
        thisMonth: 'Ce Mois',
        timeline: 'Chronologie des Découvertes',
        rarityDistribution: 'Distribution de Rareté',
        noDataYet: 'Pas encore de données',
        search: 'Rechercher',
        filterByStatus: 'Filtrer par statut',
        allStatus: 'Tous les Statuts',
        pendingAnalysis: 'En Attente d\'Analyse',
        verified: 'Vérifié',
        reported: 'Signalé',
        shareDiscovery: 'Partager Découverte',
        copyLink: 'Copier Lien',
        copied: 'Copié!',
        shareVia: 'Partager via',
        welcomeBack: 'Bienvenue',
        loginToContinue: 'Connectez-vous pour continuer vers Archeos',
        loginWithGoogle: 'Continuer avec Google',
        loginWithMicrosoft: 'Continuer avec Microsoft',
        orContinueWith: 'Ou continuez avec',
        email: 'E-mail',
        password: 'Mot de passe',
        login: 'Connexion',
        noAccount: 'Pas de compte?',
        createAccount: 'Créer un Compte',
        continueAsGuest: 'Continuer en tant qu\'Invité',
        guestLimitations: 'Certaines fonctionnalités seront limitées',
        catAll: 'Tous',
        catCoins: 'Monnaies',
        catPipes: 'Pipes',
        catJewelry: 'Bijoux',
        catWeapons: 'Armes',
        catTools: 'Outils',
        catPottery: 'Céramique',
        catOther: 'Autre',
        
        // Admin
        accessDenied: 'Accès Refusé',
        adminAccessRequired: 'Accès administrateur requis.',
        adminPanel: 'Panneau Admin',
        users: 'Utilisateurs',
        user: 'Utilisateur',
        actions: 'Actions',
        allStatuses: 'Tous les Statuts',
        discovery: 'Découverte',
        finder: 'Découvreur',
        status: 'Statut',
        date: 'Date',
        editDiscovery: 'Modifier Découverte',
        name: 'Nom',
        finderName: 'Nom du Découvreur',
        visibility: 'Visibilité',
        public: 'Public',
        cancel: 'Annuler',
        save: 'Enregistrer',
        deleteDiscovery: 'Supprimer Découverte?',
        cannotBeUndone: 'Cela ne peut pas être annulé.',
        delete: 'Supprimer',
        searchDiscoveries: 'Rechercher découvertes...',
        
        // Admin Experts
        expertsCount: 'experts',
        addExpert: 'Ajouter Expert',
        specialization: 'Spécialisation',
        institution: 'Institution',
        editExpert: 'Modifier Expert',
        nameRequired: 'Nom *',
        specializationRequired: 'Spécialisation *',
        emailRequired: 'E-mail *',
        phone: 'Téléphone',
        location: 'Lieu',
        imageUrl: 'URL Image',
        bio: 'Biographie',
        available: 'Disponible',
        unavailable: 'Indisponible',
        pinned: 'Épinglé (afficher en haut)',
        deleteExpert: 'Supprimer Expert?',
        
        // Admin Reports
        reference: 'Référence',
        
        // Admin Users
        searchUsers: 'Rechercher utilisateurs...',
        role: 'Rôle',
        joined: 'Rejoint',
        changeRole: 'Changer Rôle',
        unknown: 'Inconnu',
        
        // Discoveries page
        fromAllUsers: 'de tous les utilisateurs',
        
        // Government Report
        reportToGovernmentFull: 'Signaler au Gouvernement',
        reportToRCE: 'Signalez votre trouvaille à Rijksdienst voor het Cultureel Erfgoed (RCE)',
        reportSaved: 'Rapport enregistré! Ouvrez maintenant le formulaire gouvernemental et copiez chaque valeur ci-dessous. Cliquez sur une valeur pour la copier.',
        valuesToFill: 'Valeurs à remplir dans le formulaire gouvernemental',
        openForm: 'Ouvrir Formulaire',
        notAvailable: '— non disponible —',
        coordinateNote: '⚠️ Note: Les coordonnées X et Y sont en degrés décimaux (WGS84). Le formulaire utilise RD New (Rijksdriehoek) — vous devrez peut-être les convertir. Utilisez epsg.io/transform pour convertir. N\'oubliez pas non plus de télécharger des photos de face, de dos et de côté.',
        doneGoToReports: 'Terminé — Aller aux Rapports',
        selectDiscoveryToReport: 'Sélectionnez quelle découverte vous souhaitez signaler. Nous vérifierons si toutes les informations requises sont disponibles et vous aiderons à remplir le formulaire gouvernemental.',
        noDiscoveriesYet: 'Vous n\'avez pas encore de découvertes. Ajoutez-en une d\'abord.',
        noLocation: 'Pas de lieu',
        noDate: 'Pas de date',
        alreadyReported: 'Déjà signalé',
        reviewCheckInfo: 'Réviser & Vérifier Informations',
        infoCheckFor: 'Vérification des informations pour:',
        missingInfo: 'Certaines informations manquent',
        fillMissingFields: 'Veuillez remplir les champs manquants ci-dessous afin que le formulaire gouvernemental puisse être rempli correctement.',
        noCoordinates: '⚠️ Aucune coordonnée de lieu trouvée',
        goBackAddLocation: 'Revenez à cette découverte et ajoutez un emplacement sur la carte.',
        toponiem: 'Toponiem *',
        toponiemHint: '(nom du champ/rue/eau où trouvé)',
        toponiemPlaceholder: 'par ex. Binnenveld, Maas, Dorpsstraat',
        detectionMethodLabel: 'Méthode de détection (Vondstverwerving) *',
        selectOption: 'Sélectionner...',
        metalDetector: 'Détecteur de métaux',
        digging: 'Fouille (graafwerk)',
        surfaceFind: 'Trouvaille de surface (kartering)',
        dredging: 'Dragage (baggerwerk)',
        borehole: 'Forage (boring)',
        diving: 'Plongée',
        conditionLabel: 'Condition (Toestand) *',
        complete: 'Complet',
        fragment: 'Fragment',
        notApplicable: 'S/O',
        materialLabel: 'Matériau (Materiaal) *',
        materialPlaceholder: 'par ex. Bronze, Argent, Argile...',
        descriptionNotes: 'Description / notes (Toelichting) *',
        descriptionPlaceholder: 'Décrivez la trouvaille en détail: dimensions, marques, détails de condition, etc.',
        additionalDetails: 'Détails supplémentaires',
        optional: '(optionnel mais utile)',
        plaats: 'Plaats',
        plaatsHint: '(ville/village le plus proche)',
        plaatsPlaceholder: 'par ex. Utrecht, Amsterdam',
        aantal: 'Aantal',
        aantalHint: '(nombre de trouvailles)',
        currentStorage: 'Stockage actuel',
        currentStorageHint: '(où est la trouvaille maintenant?)',
        currentStoragePlaceholder: 'par ex. À la maison, dans une boîte',
        extraNotes: 'Notes supplémentaires pour toelichting',
        extraNotesPlaceholder: 'Détails supplémentaires sur la trouvaille...',
        whenYouClick: 'Lorsque vous cliquez sur "Ouvrir Formulaire", nous ouvrirons le formulaire officiel RCE avec toutes vos informations pré-remplies. Vous devrez peut-être encore télécharger des photos et vérifier manuellement le format des coordonnées.',
        continueToChecklist: 'Continuer vers Liste de Contrôle',
        
        // Reports page
        newReport: 'Nouveau Rapport',
        pending: 'En attente',
        deleteReport: 'Supprimer rapport?',
        deleteReportWarning: 'Cela supprimera le rapport et marquera la découverte comme "pas encore signalée". Cela ne peut pas être annulé.',
        view: 'Voir',
        
        // Share Dialog
        archeos: 'ArcheOS',
        whatsapp: 'WhatsApp',
        xTwitter: 'X',
        facebook: 'Facebook',
        more: 'Plus',
        
        // Discovery Map
        searchLocation: 'Rechercher un lieu...',
        unknownObject: 'Objet Inconnu',
        locationNotSpecified: 'Lieu non spécifié',
    },
    es: {
        home: 'Inicio',
        discoveries: 'Hallazgos',
        myDiscoveries: 'Mis Hallazgos',
        community: 'Comunidad',
        map: 'Mapa',
        experts: 'Expertos',
        reports: 'Informes',
        statistics: 'Estadísticas',
        settings: 'Configuración',
        admin: 'Admin',
        editLabel: 'Editar etiqueta',
        editTimeLabel: 'Editar etiqueta de tiempo',
        useMyLocation: 'Usar Mi Ubicación',
        geoNotSupported: 'La geolocalización no es compatible con su navegador',
        geoError: 'No se pudo recuperar su ubicación',
        welcome: 'Archeos',
        tagline: 'Descubre, identifica y documenta hallazgos arqueológicos con análisis de IA',
        newDiscovery: 'Nuevo Hallazgo',
        viewMap: 'Ver Mapa',
        contactExpert: 'Contactar Experto',
        totalDiscoveries: 'Total Hallazgos',
        identified: 'Identificados',
        reportsFiled: 'Informes',
        recentDiscoveries: 'Hallazgos Recientes',
        viewAll: 'Ver Todo',
        noDiscoveries: 'Sin hallazgos',
        startBy: 'Comience subiendo una foto',
        addFirst: 'Agregar Primer Hallazgo',
        uploadPhoto: 'Subir Foto',
        analyzeWithAI: 'Analizar con IA',
        analyzing: 'Analizando...',
        scanning: 'Escaneando...',
        researching: 'Investigando...',
        uploadingImages: 'Subiendo imágenes...',
        helpsAI: 'ayuda a la IA a identificar con más precisión',
        markLocation: 'Marcar Ubicación',
        clickMap: 'Haga clic en el mapa para indicar dónde encontró este objeto',
        addDetails: 'Agregar Detalles',
        discoveryName: 'Nombre del Hallazgo',
        locationName: 'Nombre del Lugar',
        discoveryDate: 'Fecha del Hallazgo',
        notes: 'Notas',
        saveDiscovery: 'Guardar Hallazgo',
        back: 'Atrás',
        continue: 'Continuar',
        advancedMode: 'Modo Avanzado',
        depthFound: 'Profundidad Encontrada',
        soilType: 'Tipo de Suelo',
        condition: 'Condición',
        detectionMethod: 'Método de Detección',
        additionalPhotos: 'Fotos Adicionales',
        aiAnalysis: 'Resultados del Análisis IA',
        period: 'Período',
        origin: 'Origen',
        material: 'Material',
        confidence: 'confianza',
        similarFinds: 'Hallazgos Similares',
        howToStore: 'Cómo Almacenar',
        databaseReferences: 'Referencias de Base de Datos',
        share: 'Compartir',
        reportToGov: 'Reportar al Gobierno',
        foundBy: 'Encontrado por',
        foundOn: 'Encontrado el',
        private: 'Privado',
        makePrivate: 'Hacer Privado',
        makePublic: 'Hacer Público',
        appearance: 'Apariencia',
        darkMode: 'Modo Oscuro',
        language: 'Idioma',
        selectLanguage: 'Seleccione su idioma',
        toggleTheme: 'Cambiar entre claro y oscuro',
        notifications: 'Notificaciones',
        emailNotifications: 'Notificaciones por Correo',
        account: 'Cuenta',
        signOut: 'Cerrar Sesión',
        signIn: 'Iniciar Sesión',
        loginRequired: 'Inicio de Sesión Requerido',
        loginToAccess: 'Por favor inicie sesión para acceder a esta función',
        statisticsTitle: 'Estadísticas y Logros',
        trackYourDiscoveries: 'Rastrea tus hallazgos arqueológicos y logros',
        thisMonth: 'Este Mes',
        timeline: 'Línea de Tiempo de Hallazgos',
        rarityDistribution: 'Distribución de Rareza',
        noDataYet: 'Sin datos aún',
        search: 'Buscar',
        filterByStatus: 'Filtrar por estado',
        allStatus: 'Todos los Estados',
        pendingAnalysis: 'Pendiente de Análisis',
        verified: 'Verificado',
        reported: 'Reportado',
        shareDiscovery: 'Compartir Hallazgo',
        copyLink: 'Copiar Enlace',
        copied: '¡Copiado!',
        shareVia: 'Compartir vía',
        welcomeBack: 'Bienvenido',
        loginToContinue: 'Inicia sesión para continuar a Archeos',
        loginWithGoogle: 'Continuar con Google',
        loginWithMicrosoft: 'Continuar con Microsoft',
        orContinueWith: 'O continúa con',
        email: 'Correo electrónico',
        password: 'Contraseña',
        login: 'Iniciar Sesión',
        noAccount: '¿No tienes cuenta?',
        createAccount: 'Crear Cuenta',
        continueAsGuest: 'Continuar como Invitado',
        guestLimitations: 'Algunas funciones serán limitadas',
        catAll: 'Todos',
        catCoins: 'Monedas',
        catPipes: 'Pipas',
        catJewelry: 'Joyería',
        catWeapons: 'Armas',
        catTools: 'Herramientas',
        catPottery: 'Cerámica',
        catOther: 'Otro',
        
        // Admin
        accessDenied: 'Acceso Denegado',
        adminAccessRequired: 'Se requiere acceso de administrador.',
        adminPanel: 'Panel Admin',
        users: 'Usuarios',
        user: 'Usuario',
        actions: 'Acciones',
        allStatuses: 'Todos los Estados',
        discovery: 'Hallazgo',
        finder: 'Descubridor',
        status: 'Estado',
        date: 'Fecha',
        editDiscovery: 'Editar Hallazgo',
        name: 'Nombre',
        finderName: 'Nombre del Descubridor',
        visibility: 'Visibilidad',
        public: 'Público',
        cancel: 'Cancelar',
        save: 'Guardar',
        deleteDiscovery: 'Eliminar Hallazgo?',
        cannotBeUndone: 'Esto no se puede deshacer.',
        delete: 'Eliminar',
        searchDiscoveries: 'Buscar hallazgos...',
        
        // Admin Experts
        expertsCount: 'expertos',
        addExpert: 'Agregar Experto',
        specialization: 'Especialización',
        institution: 'Institución',
        editExpert: 'Editar Experto',
        nameRequired: 'Nombre *',
        specializationRequired: 'Especialización *',
        emailRequired: 'Correo *',
        phone: 'Teléfono',
        location: 'Ubicación',
        imageUrl: 'URL Imagen',
        bio: 'Biografía',
        available: 'Disponible',
        unavailable: 'No disponible',
        pinned: 'Fijado (mostrar arriba)',
        deleteExpert: 'Eliminar Experto?',
        
        // Admin Reports
        reference: 'Referencia',
        
        // Admin Users
        searchUsers: 'Buscar usuarios...',
        role: 'Rol',
        joined: 'Unido',
        changeRole: 'Cambiar Rol',
        unknown: 'Desconocido',
        
        // Discoveries page
        fromAllUsers: 'de todos los usuarios',
        
        // Government Report
        reportToGovernmentFull: 'Reportar al Gobierno',
        reportToRCE: 'Reporte su hallazgo a Rijksdienst voor het Cultureel Erfgoed (RCE)',
        reportSaved: '¡Informe guardado! Ahora abra el formulario del gobierno y copie cada valor a continuación. Haga clic en cualquier valor para copiarlo.',
        valuesToFill: 'Valores para completar en el formulario del gobierno',
        openForm: 'Abrir Formulario',
        notAvailable: '— no disponible —',
        coordinateNote: '⚠️ Nota: Las coordenadas X e Y están en grados decimales (WGS84). El formulario usa RD New (Rijksdriehoek) — es posible que deba convertirlas. Use epsg.io/transform para convertir. Tampoco olvide subir fotos del frente, atrás y lateral.',
        doneGoToReports: 'Hecho — Ir a Informes',
        selectDiscoveryToReport: 'Seleccione qué hallazgo desea reportar. Verificaremos si toda la información requerida está disponible y lo ayudaremos a completar el formulario del gobierno.',
        noDiscoveriesYet: 'Aún no tiene hallazgos. Agregue uno primero.',
        noLocation: 'Sin ubicación',
        noDate: 'Sin fecha',
        alreadyReported: 'Ya reportado',
        reviewCheckInfo: 'Revisar & Verificar Información',
        infoCheckFor: 'Verificación de información para:',
        missingInfo: 'Falta alguna información',
        fillMissingFields: 'Complete los campos faltantes a continuación para que el formulario del gobierno pueda completarse correctamente.',
        noCoordinates: '⚠️ No se encontraron coordenadas de ubicación',
        goBackAddLocation: 'Regrese a este hallazgo y agregue una ubicación en el mapa.',
        toponiem: 'Toponiem *',
        toponiemHint: '(nombre del campo/calle/agua donde se encontró)',
        toponiemPlaceholder: 'ej. Binnenveld, Maas, Dorpsstraat',
        detectionMethodLabel: 'Método de detección (Vondstverwerving) *',
        selectOption: 'Seleccionar...',
        metalDetector: 'Detector de metales',
        digging: 'Excavación (graafwerk)',
        surfaceFind: 'Hallazgo superficial (kartering)',
        dredging: 'Dragado (baggerwerk)',
        borehole: 'Perforación (boring)',
        diving: 'Buceo',
        conditionLabel: 'Condición (Toestand) *',
        complete: 'Completo',
        fragment: 'Fragmento',
        notApplicable: 'N/A',
        materialLabel: 'Material (Materiaal) *',
        materialPlaceholder: 'ej. Bronce, Plata, Arcilla...',
        descriptionNotes: 'Descripción / notas (Toelichting) *',
        descriptionPlaceholder: 'Describa el hallazgo con más detalle: dimensiones, marcas, detalles de condición, etc.',
        additionalDetails: 'Detalles adicionales',
        optional: '(opcional pero útil)',
        plaats: 'Plaats',
        plaatsHint: '(ciudad/pueblo más cercano)',
        plaatsPlaceholder: 'ej. Utrecht, Amsterdam',
        aantal: 'Aantal',
        aantalHint: '(número de hallazgos)',
        currentStorage: 'Almacenamiento actual',
        currentStorageHint: '(¿dónde está el hallazgo ahora?)',
        currentStoragePlaceholder: 'ej. En casa, en una caja',
        extraNotes: 'Notas adicionales para toelichting',
        extraNotesPlaceholder: 'Detalles adicionales sobre el hallazgo...',
        whenYouClick: 'Cuando haga clic en "Abrir Formulario", abriremos el formulario oficial RCE con toda su información prellenada. Es posible que aún necesite subir fotos y verificar manualmente el formato de coordenadas.',
        continueToChecklist: 'Continuar a Lista de Verificación',
        
        // Reports page
        newReport: 'Nuevo Informe',
        pending: 'Pendiente',
        deleteReport: 'Eliminar informe?',
        deleteReportWarning: 'Esto eliminará el informe y marcará el hallazgo como "aún no reportado". Esto no se puede deshacer.',
        view: 'Ver',
        
        // Share Dialog
        archeos: 'ArcheOS',
        whatsapp: 'WhatsApp',
        xTwitter: 'X',
        facebook: 'Facebook',
        more: 'Más',
        
        // Discovery Map
        searchLocation: 'Buscar ubicación...',
        unknownObject: 'Objeto Desconocido',
        locationNotSpecified: 'Ubicación no especificada',
    },
    el: {
        // General
        home: 'Αρχική',
        discoveries: 'Ανακαλύψεις',
        myDiscoveries: 'Οι Ανακαλύψεις μου',
        community: 'Κοινότητα',
        map: 'Χάρτης',
        experts: 'Ειδικοί',
        reports: 'Αναφορές',
        statistics: 'Στατιστικά',
        settings: 'Ρυθμίσεις',
        admin: 'Διαχείριση',
        editLabel: 'Επεξεργασία ετικέτας',
        editTimeLabel: 'Επεξεργασία χρονικής ετικέτας',
        useMyLocation: 'Χρήση της Τοποθεσίας μου',
        geoNotSupported: 'Η γεωεντοπισμός δεν υποστηρίζεται από το πρόγραμμα περιήγησής σας',
        geoError: 'Δεν ήταν δυνατή η ανάκτηση της τοποθεσίας σας',
        welcome: 'Archeos',
        tagline: 'Ανακαλύψτε, ταυτοποιήστε και τεκμηριώστε αρχαιολογικά ευρήματα με ανάλυση τεχνητής νοημοσύνης',
        newDiscovery: 'Νέα Ανακάλυψη',
        viewMap: 'Προβολή Χάρτη',
        contactExpert: 'Επικοινωνία με Ειδικό',
        totalDiscoveries: 'Συνολικές Ανακαλύψεις',
        identified: 'Ταυτοποιημένα',
        reportsFiled: 'Υποβλήθηκαν Αναφορές',
        recentDiscoveries: 'Πρόσφατες Ανακαλύψεις',
        viewAll: 'Προβολή Όλων',
        noDiscoveries: 'Δεν υπάρχουν ανακαλύψεις ακόμα',
        startBy: 'Ξεκινήστε ανεβάζοντας μια φωτογραφία ενός αρχαιολογικού ευρήματος',
        addFirst: 'Προσθήκη Πρώτης Ανακάλυψης',
        uploadPhoto: 'Μεταφόρτωση Φωτογραφίας',
        analyzeWithAI: 'Ανάλυση με AI',
        analyzing: 'Ανάλυση...',
        scanning: 'Σάρωση...',
        researching: 'Έρευνα...',
        uploadingImages: 'Μεταφόρτωση εικόνων...',
        helpsAI: 'βοηθά την AI να εντοπίσει με μεγαλύτερη ακρίβεια',
        markLocation: 'Σημείωση Τοποθεσίας Ανακάλυψης',
        clickMap: 'Κάντε κλικ στον χάρτη για να σημειώσετε πού βρήκατε αυτό το αντικείμενο',
        addDetails: 'Προσθήκη Λεπτομερειών',
        discoveryName: 'Όνομα Ανακάλυψης',
        locationName: 'Όνομα Τοποθεσίας',
        discoveryDate: 'Ημερομηνία Ανακάλυψης',
        notes: 'Σημειώσεις',
        saveDiscovery: 'Αποθήκευση Ανακάλυψης',
        back: 'Πίσω',
        continue: 'Συνέχεια',
        advancedMode: 'Προχωρημένη Λειτουργία',
        depthFound: 'Βάθος Εύρεσης',
        soilType: 'Τύπος Εδάφους',
        condition: 'Κατάσταση',
        detectionMethod: 'Μέθοδος Ανίχνευσης',
        additionalPhotos: 'Επιπλέον Φωτογραφίες',
        aiAnalysis: 'Αποτελέσματα AI Ανάλυσης',
        period: 'Περίοδος',
        origin: 'Προέλευση',
        material: 'Υλικό',
        confidence: 'εμπιστοσύνη',
        similarFinds: 'Παρόμοια Ευρήματα',
        howToStore: 'Πώς να Αποθηκεύσετε',
        databaseReferences: 'Αναφορές Βάσεων Δεδομένων',
        share: 'Κοινοποίηση',
        reportToGov: 'Αναφορά στην Κυβέρνηση',
        foundBy: 'Βρέθηκε από',
        foundOn: 'Βρέθηκε στις',
        private: 'Ιδιωτικό',
        makePrivate: 'Μετατροπή σε Ιδιωτικό',
        makePublic: 'Μετατροπή σε Δημόσιο',
        appearance: 'Εμφάνιση',
        darkMode: 'Σκοτεινή Λειτουργία',
        language: 'Γλώσσα',
        selectLanguage: 'Επιλέξτε τη γλώσσα σας',
        toggleTheme: 'Εναλλαγή μεταξύ φωτεινής και σκοτεινής λειτουργίας',
        notifications: 'Ειδοποιήσεις',
        emailNotifications: 'Ειδοποιήσεις Email',
        account: 'Λογαριασμός',
        signOut: 'Αποσύνδεση',
        signIn: 'Σύνδεση',
        loginRequired: 'Απαιτείται Σύνδεση',
        loginToAccess: 'Συνδεθείτε για να αποκτήσετε πρόσβαση σε αυτήν τη λειτουργία',
        statisticsTitle: 'Στατιστικά & Επιτεύγματα',
        trackYourDiscoveries: 'Παρακολουθήστε τις αρχαιολογικές ανακαλύψεις και τα επιτεύγματά σας',
        thisMonth: 'Αυτός ο Μήνας',
        timeline: 'Χρονοδιάγραμμα Ανακαλύψεων',
        rarityDistribution: 'Κατανομή Σπανιότητας',
        noDataYet: 'Δεν υπάρχουν δεδομένα ακόμα',
        search: 'Αναζήτηση',
        filterByStatus: 'Φιλτράρισμα κατά κατάσταση',
        allStatus: 'Όλες οι Καταστάσεις',
        pendingAnalysis: 'Εκκρεμεί Ανάλυση',
        verified: 'Επαληθευμένο',
        reported: 'Αναφέρθηκε',
        shareDiscovery: 'Κοινοποίηση Ανακάλυψης',
        copyLink: 'Αντιγραφή Συνδέσμου',
        copied: 'Αντιγράφηκε!',
        shareVia: 'Κοινοποίηση μέσω',
        welcomeBack: 'Καλώς ορίσατε ξανά',
        loginToContinue: 'Συνδεθείτε για να συνεχίσετε στο Archeos',
        loginWithGoogle: 'Συνέχεια με Google',
        loginWithMicrosoft: 'Συνέχεια με Microsoft',
        orContinueWith: 'Ή συνεχίστε με',
        email: 'Email',
        password: 'Κωδικός',
        login: 'Σύνδεση',
        noAccount: 'Δεν έχετε λογαριασμό;',
        createAccount: 'Δημιουργία Λογαριασμού',
        continueAsGuest: 'Συνέχεια ως Επισκέπτης',
        guestLimitations: 'Ορισμένες λειτουργίες θα είναι περιορισμένες',
        catAll: 'Όλα',
        catCoins: 'Νομίσματα',
        catPipes: 'Πίπες',
        catJewelry: 'Κοσμήματα',
        catWeapons: 'Όπλα',
        catTools: 'Εργαλεία',
        catPottery: 'Κεραμική',
        catOther: 'Άλλα',
        accessDenied: 'Απαγορεύεται η Πρόσβαση',
        adminAccessRequired: 'Απαιτείται πρόσβαση διαχειριστή.',
        adminPanel: 'Πάνελ Διαχείρισης',
        users: 'Χρήστες',
        user: 'Χρήστης',
        actions: 'Ενέργειες',
        allStatuses: 'Όλες οι Καταστάσεις',
        discovery: 'Ανακάλυψη',
        finder: 'Εύρετης',
        status: 'Κατάσταση',
        date: 'Ημερομηνία',
        editDiscovery: 'Επεξεργασία Ανακάλυψης',
        name: 'Όνομα',
        finderName: 'Όνομα Εύρετη',
        visibility: 'Ορατότητα',
        public: 'Δημόσιο',
        cancel: 'Ακύρωση',
        save: 'Αποθήκευση',
        deleteDiscovery: 'Διαγραφή Ανακάλυψης;',
        cannotBeUndone: 'Αυτό δεν μπορεί να αναιρεθεί.',
        delete: 'Διαγραφή',
        searchDiscoveries: 'Αναζήτηση ανακαλύψεων...',
        expertsCount: 'ειδικοί',
        addExpert: 'Προσθήκη Ειδικού',
        specialization: 'Εξειδίκευση',
        institution: 'Ιδρυμα',
        editExpert: 'Επεξεργασία Ειδικού',
        nameRequired: 'Όνομα *',
        specializationRequired: 'Εξειδίκευση *',
        emailRequired: 'Email *',
        phone: 'Τηλέφωνο',
        location: 'Τοποθεσία',
        imageUrl: 'URL Εικόνας',
        bio: 'Βιογραφία',
        available: 'Διαθέσιμος',
        unavailable: 'Μη Διαθέσιμος',
        pinned: 'Καρφιτσωμένο',
        deleteExpert: 'Διαγραφή Ειδικού;',
        reference: 'Αναφορά',
        searchUsers: 'Αναζήτηση χρηστών...',
        role: 'Ρόλος',
        joined: 'Εγγραφή',
        changeRole: 'Αλλαγή Ρόλου',
        unknown: 'Άγνωστο',
        fromAllUsers: 'από όλους τους χρήστες',
        reportToGovernmentFull: 'Αναφορά στην Κυβέρνηση',
        reportToRCE: 'Αναφέρετε το εύρημά σας στην Rijksdienst voor het Cultureel Erfgoed (RCE)',
        reportSaved: 'Η αναφορά αποθηκεύτηκε! Τώρα ανοίξτε την κυβερνητική φόρμα και αντιγράψτε κάθε τιμή παρακάτω.',
        valuesToFill: 'Τιμές για συμπλήρωση στην κυβερνητική φόρμα',
        openForm: 'Άνοιγμα Φόρμας',
        notAvailable: '— δεν είναι διαθέσιμο —',
        coordinateNote: '⚠️ Σημείωση: Οι συντεταγμένες X και Y είναι σε δεκαδικές μοίρες (WGS84). Η φόρμα χρησιμοποιεί RD New (Rijksdriehoek) — ίσως χρειαστεί να τις μετατρέψετε.',
        doneGoToReports: 'Ολοκληρώθηκε — Πήγαινε στις Αναφορές',
        selectDiscoveryToReport: 'Επιλέξτε ποια ανακάλυψη θέλετε να αναφέρετε.',
        noDiscoveriesYet: 'Δεν έχετε ανακαλύψεις ακόμα. Προσθέστε μία πρώτα.',
        noLocation: 'Χωρίς τοποθεσία',
        noDate: 'Χωρίς ημερομηνία',
        alreadyReported: 'Ήδη αναφέρθηκε',
        reviewCheckInfo: 'Επισκόπηση & Έλεγχος Πληροφοριών',
        infoCheckFor: 'Έλεγχος πληροφοριών για:',
        missingInfo: 'Λείπουν κάποιες πληροφορίες',
        fillMissingFields: 'Συμπληρώστε τα παρακάτω πεδία που λείπουν.',
        noCoordinates: '⚠️ Δεν βρέθηκαν συντεταγμένες τοποθεσίας',
        goBackAddLocation: 'Επιστρέψτε σε αυτήν την ανακάλυψη και προσθέστε μια τοποθεσία στον χάρτη.',
        toponiem: 'Τοπωνύμιο *',
        detectionMethodLabel: 'Μέθοδος ανίχνευσης (Vondstverwerving) *',
        selectOption: 'Επιλογή...',
        metalDetector: 'Ανιχνευτής μετάλλων',
        digging: 'Σκάψιμο',
        surfaceFind: 'Εύρημα επιφάνειας',
        conditionLabel: 'Κατάσταση (Toestand) *',
        complete: 'Ολοκληρωμένο',
        fragment: 'Τμήμα',
        notApplicable: 'Δ/Ε',
        materialLabel: 'Υλικό (Materiaal) *',
        descriptionNotes: 'Περιγραφή / σημειώσεις (Toelichting) *',
        additionalDetails: 'Επιπλέον λεπτομέρειες',
        optional: '(προαιρετικό αλλά χρήσιμο)',
        extraNotes: 'Επιπλέον σημειώσεις',
        whenYouClick: 'Όταν κάνετε κλικ στο "Άνοιγμα Φόρμας", θα ανοίξουμε την επίσημη φόρμα RCE με όλες τις πληροφορίες σας προσυμπληρωμένες.',
        continueToChecklist: 'Συνέχεια στη Λίστα Ελέγχου',
        newReport: 'Νέα Αναφορά',
        pending: 'Εκκρεμεί',
        deleteReport: 'Διαγραφή αναφοράς;',
        deleteReportWarning: 'Αυτό θα διαγράψει την αναφορά. Δεν μπορεί να αναιρεθεί.',
        view: 'Προβολή',
        archeos: 'ArcheOS',
        whatsapp: 'WhatsApp',
        xTwitter: 'X',
        facebook: 'Facebook',
        more: 'Περισσότερα',
        searchLocation: 'Αναζήτηση τοποθεσίας...',
        unknownObject: 'Άγνωστο Αντικείμενο',
        locationNotSpecified: 'Η τοποθεσία δεν έχει καθοριστεί',
        unknownLocation: 'Άγνωστη τοποθεσία',
        step1: 'Βήμα 1',
        step2: 'Βήμα 2',
        step3: 'Βήμα 3',
        optionalDetails: 'Προαιρετικές λεπτομέρειες',
        selectPlaceholder: 'Επιλογή...',
        usefulReferences: 'Χρήσιμες αναφορές για το εύρημά σας:',
        aiFailed: 'Η ανάλυση AI απέτυχε. Δοκιμάστε ξανά.',
        discoveryLocation: 'Τοποθεσία Ανακάλυψης',
        coins: 'Νομίσματα',
        pipes: 'Πίπες',
        jewelry: 'Κοσμήματα',
        weapons: 'Όπλα',
        tools: 'Εργαλεία',
        pottery: 'Κεραμική',
        other: 'Άλλο',
        all: 'Όλα',
        yourDiscoveriesOnMap: 'Οι ανακαλύψεις σας στον χάρτη',
        analytics: 'Αναλύσεις',
        credits: 'Πίστωση',
    },
};

const LanguageContext = createContext();

const getDefaultLanguage = () => {
    const stored = localStorage.getItem('language');
    if (stored && translations[stored]) {
        return stored;
    }
    
    const browserLang = navigator.language || navigator.languages?.[0] || 'en';
    const langCode = browserLang.split('-')[0].toLowerCase();
    
    if (translations[langCode]) {
        return langCode;
    }
    
    if (browserLang.startsWith('nl')) return 'nl';
    if (browserLang.startsWith('de')) return 'de';
    if (browserLang.startsWith('fr')) return 'fr';
    if (browserLang.startsWith('es')) return 'es';
    if (browserLang.startsWith('el')) return 'el';
    
    return 'en';
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(getDefaultLanguage);
    const [darkMode, setDarkMode] = useState(() => localStorage.getItem('darkMode') === 'true');

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    useEffect(() => {
        localStorage.setItem('darkMode', darkMode);
        if (darkMode) {
            document.documentElement.classList.add('dark');
            document.body.style.backgroundColor = '#111827';
        } else {
            document.documentElement.classList.remove('dark');
            document.body.style.backgroundColor = '#fdf6ef';
        }
    }, [darkMode]);

    const t = (key) => translations[language]?.[key] || translations.en[key] || key;
    const toggleDarkMode = () => setDarkMode(prev => !prev);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, darkMode, setDarkMode, toggleDarkMode, t, translations }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        return {
            language: localStorage.getItem('language') || 'en',
            darkMode: localStorage.getItem('darkMode') === 'true',
            t: (key) => translations[localStorage.getItem('language') || 'en']?.[key] || translations.en[key] || key,
            setLanguage: () => {},
            setDarkMode: () => {},
            toggleDarkMode: () => {},
        };
    }
    return context;
}

export { translations };