name = "embeddings"
main = "index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[env.production.bindings]]
name = "AI"
type = "ai"

[[env.preview.bindings]]
name = "AI"
type = "ai"

[observability]
enabled = true